### ISSUE TITLE
Setup guidelines don't work

### ISSUE THREAD

**Issue by MasterAir** [throneteki/throneteki#2987]
When running the `server/scripts/fetchclient.js` script to setup a dev environment the script fails with the following error message:

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'js' of undefined
    at fetchClient (/Users/danieljones/sandbox/throneteki/server/scripts/fetchclient.js:35:84)
    at async /Users/danieljones/sandbox/throneteki/server/scripts/fetchclient.js:56:5
(node:1324) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1324) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I believe the file `https://theironthrone.net/vendor-assets.html` is missing. Is this temporary? Is there an alternate build process?

Thanks

**Comment by EvadLhorg** [comment]
Hi! I think i encountered the same error, try commenting out the writeFile for the vendorAssets, think that solved it for me. If not, let me know!

**Comment by MasterAir** [comment]
Thanks, I tried that.

I commented line 32 
```
-- await writeFile('./vendor-assets.json', JSON.stringify(vendorAssets));
++ // await writeFile('./vendor-assets.json', JSON.stringify(vendorAssets));
```
I still get the same error.

**Comment by EvadLhorg** [comment]
Hello again. Just looked at your error message again and saw that it is line 35 that is throwing your error. Maybe try commenting out that one instead of line 32.
